# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'
- task: powershell@2
  displayName: DirectoryList
  inputs:
    targetType: inline
    script: dir $(build.artifactStagingDirectory) -s
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:AdventureWorks ' #/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    configuration: '$(buildConfiguration)'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    msbuildArgs: '/t:AdventureWorksTesting' #/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    configuration: '$(buildConfiguration)'
- task: powershell@2
  displayName: DirectoryList
  inputs:
    targetType: inline
    script: dir -s
- task: PublishBuildArtifacts@1
  displayName: PublishDatabase
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/bin/Release/'
    ArtifactName: 'AdventureWorks'
    publishLocation: 'Container'
- task: PublishBuildArtifacts@1
  displayName: PublishDatabaseTests
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/AdventureWorksTesting/bin/Release/'
    ArtifactName: 'AdventureWorksTesting'
    publishLocation: 'Container'
